In [15]:
import numpy as np

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
print(l1)
print(l2)

[[  9.99134323e-01   8.73873054e-01   9.96184558e-01   9.58712579e-01]
 [  9.25357164e-01   9.70477212e-01   8.87669682e-01   1.48854588e-02]
 [  8.87950935e-01   8.25578461e-01   8.17743303e-01   1.84811622e-02]
 [  7.84433364e-02   9.57368240e-01   1.19561645e-01   1.22526533e-05]]
[[ 0.00395374]
 [ 0.99568925]
 [ 0.9967036 ]
 [ 0.00477395]]


In [50]:
import numpy as np

def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
np.random.seed(1)
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for iter in range(60000):
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    l2_error = y - l2
    l1_error = l2_delta.dot(syn1.T)
    if (iter% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))
    l2_delta = l2_error*nonlin(l2,deriv=True)
    l1_delta = l1_error * nonlin(l1,deriv=True)
    syn1 += l1.T.dot(l2_delta)
    syn0 += np.dot(l0.T,l1_delta)
print(l1)
print("******")
print(l2)

Error:0.496410031903
Error:0.00858588316689
Error:0.00579050143742
Error:0.00463004201792
Error:0.00395951744543
Error:0.00351079492493
[[  7.26343184e-01   1.16294641e-01   9.26426559e-01   9.97128719e-01]
 [  1.66926165e-01   3.90362389e-04   1.66098203e-02   8.96837818e-01]
 [  9.96224420e-01   8.95394190e-01   2.22630516e-02   8.38568558e-01]
 [  9.52197755e-01   2.47713810e-02   3.05420750e-05   1.15073556e-01]]
******
[[ 0.00260688]
 [ 0.99672182]
 [ 0.9970168 ]
 [ 0.00386831]]


In [41]:
2*np.random.random((3,1)) - 1

array([[-0.62747958],
       [-0.30887855],
       [-0.20646505]])

In [6]:
l1

array([[  5.84307600e-01,   8.93899190e-01,   4.34299805e-01,
          1.05394749e-01],
       [  6.01780761e-01,   3.58064807e-02,   9.78333877e-01,
          8.23103333e-05],
       [  6.00643001e-01,   9.99929175e-01,   9.75896439e-01,
          9.55627151e-01],
       [  6.17878566e-01,   9.84185179e-01,   9.99580248e-01,
          1.48247453e-02]])